
OBSTACLE_AVOID = True
MOVING_OBSTACLE = False

OBSTACLE_X = 10
OBSTACLE_Y = 10
OBSTACLE_DIAMETER = 1
OBSTACLE_VX = 0.0
OBSTACLE_VY = 0.0

ROBOT_DIAMETER = 0.5

#NLP solver options
MAX_ITER = 1000
MAX_TIME = 100
PRINT_LEVEL = 2
ACCEPT_TOL = 1e-6
ACCEPT_OBJ_TOL = 1e-6
PRINT_TIME = 1